### ISSUE TITLE
Overwatch Game time not being tracked?

### ISSUE THREAD

**Issue by saitho** [bartok765/galaxy_blizzard_plugin#21]
There are several issues on the GOG issue tracker that reported game time tracking was not working.

* [Overwatch PC gametime doesnt show](https://mantis2.gog.com/view.php?id=52577)
* [GOG 2.0 won't count Overwatch's hours played](https://mantis2.gog.com/view.php?id=55595)
* [Battle .net game time not tracked](https://mantis2.gog.com/view.php?id=51011)
* Partly: [osu overwatch](https://mantis2.gog.com/view.php?id=40517)
* [Overwatch not synchronised](https://mantis2.gog.com/view.php?id=37925)
* [Overwatch time not tracking](https://mantis2.gog.com/view.php?id=31829) (after switching from a manually added binary to the plugin)

We may have to check that again.

**Comment by bartok765** [comment]
55595 - probably problem with competive as you said. Maybe there is a way to get from current season, then save locally to be able to sum it later..?

**Comment by FriendsOfGalaxy** [comment]
Hello, maybe this can help:

```
2020-07-03 18:09:01,768 - root - DEBUG - Status code: 200
2020-07-03 18:09:01,769 - galaxy.api.plugin - ERROR - Unexpected exception raised in game times importer
Traceback (most recent call last):
File "C:\Users\Marlon\AppData\Local\GOG.com\Galaxy\plugins\installed\battlenet_ba170431-0649-482f-863b-d248592f1842\galaxy\api\plugin.py", line 63, in import_element
element = await self.get(id, context_)
File "C:\Users\Marlon\AppData\Local\GOG.com\Galaxy\plugins\installed\battlenet_ba170431-0649-482f-863b-d248592f1842\plugin.py", line 362, in get_game_time
total_time = await self._get_overwatch_time()
File "C:\Users\Marlon\AppData\Local\GOG.com\Galaxy\plugins\installed\battlenet_ba170431-0649-482f-863b-d248592f1842\plugin.py", line 382, in _get_overwatch_time
qp_time = player_data['playtime']['quickplay']
KeyError: 'quickplay'
2020-07-03 18:09:01,798 - galaxy.api.jsonrpc - INFO - Sending notification: method=game_time_import_failure, params={'game_id': 'prometheus', 'error': {'code': 0, 'message': 'Unknown error'}}
```

Has something changed in the API?

**Comment by saitho** [comment]
Looking at the APi request for my profile that data seems to be gone:
https://owapi.io/profile/pc/eu/saitho-2703
